# Generated by Django 6.1.1 on 2026-09-30 11:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    # `__first__` rather than migration names: this plugin is a separate repository, and
    # mutint-core is free to renumber, squash or collapse its own history without knowing
    # this file exists. `Experiment` and `Job` are created in their apps' first migrations,
    # which is all a foreign key to them needs.
    #
    # `makemigrations` emits concrete names and will never emit this; regenerating this file
    # reverts the sentinel silently. Re-apply it when you do.
    dependencies = [
        ('mutint_experiment', '__first__'),
        ('mutint_jobs', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecificityRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selection_key', models.CharField(db_index=True, max_length=64)),
                ('params', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('finished', 'Finished'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=16)),
                ('task_result_id', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('progress', models.BigIntegerField(default=0)),
                ('total', models.BigIntegerField(default=0)),
                ('error', models.TextField(blank=True, default='')),
                ('result', models.JSONField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specificity_runs', to='mutint_experiment.experiment')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='mutint_jobs.job')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
